services:
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - VITE_API_URL=https://anly.onrender.com/api # Not strictly needed anymore, but keeping for reference
    container_name: anly_frontend_prod
    restart: always
    ports:
      - "80:80"

